<?php

return [
    'default' => [
        'theme_key' => 'default',
        'label' => 'Standardwelt',
        'marker_label' => 'STD',
        'marker_symbol' => 'WELT',
        'marker_bg' => 'rgba(245, 158, 11, 0.16)',
        'marker_fg' => 'rgb(254, 243, 199)',
        'marker_border' => 'rgba(217, 119, 6, 0.62)',
        'theme_color' => '#0f0f14',
        'classes' => [
            'html' => 'world-theme-default',
            'body' => 'world-theme-default-shell',
        ],
        'css_variables' => [
            '--world-bg-top' => 'rgba(166,100,38,0.32)',
            '--world-bg-mid' => 'rgba(70,53,36,0.20)',
            '--world-bg-bottom' => '#020202',
            '--world-glow-primary' => 'rgba(166,100,38,0.30)',
            '--world-glow-secondary' => 'rgba(90,66,129,0.16)',
            '--world-texture-ink' => 'rgba(255,244,214,0.06)',
            '--world-texture-shadow' => 'rgba(0,0,0,0.24)',
            '--world-texture-opacity' => '0.46',
            '--narrative-font-size' => 'clamp(1.03rem, 1rem + 0.34vw, 1.18rem)',
            '--narrative-line-height' => '1.9',
            '--narrative-max-width' => '76ch',
            '--ui-font-size' => 'clamp(0.9rem, 0.86rem + 0.18vw, 0.98rem)',
            '--ui-line-height' => '1.45',
        ],
    ],

    'worlds' => [
        'chroniken-der-asche' => [
            'theme_key' => 'chroniken-der-asche',
            'label' => 'Chroniken der Asche',
            'marker_label' => 'CA',
            'marker_symbol' => 'ASCHE',
            'marker_bg' => 'rgb(51 28 18 / 88%)',
            'marker_fg' => '#f2c08d',
            'marker_border' => 'rgb(196 106 50 / 58%)',
            'theme_color' => '#18110f',
            'classes' => [
                'html' => 'world-theme-chroniken-der-asche',
                'body' => 'world-theme-chroniken-der-asche-shell',
            ],
            'css_variables' => [
                '--accent' => '#c46a32',
                '--accent-strong' => 'rgb(196 106 50 / 24%)',
                '--world-bg-top' => 'rgb(87 45 28 / 34%)',
                '--world-bg-mid' => 'rgb(42 31 29 / 26%)',
                '--world-bg-bottom' => '#060403',
                '--world-glow-primary' => 'rgb(196 106 50 / 26%)',
                '--world-glow-secondary' => 'rgb(120 53 15 / 18%)',
                '--narrative-font-size' => 'clamp(1.06rem, 1.02rem + 0.38vw, 1.22rem)',
                '--narrative-line-height' => '1.95',
            ],
        ],
        'klassische-fantasy' => [
            'theme_key' => 'klassische-fantasy',
            'label' => 'Klassische Fantasy',
            'marker_label' => 'KF',
            'marker_symbol' => 'MAGIE',
            'marker_bg' => 'rgb(13 43 28 / 90%)',
            'marker_fg' => '#d7c56d',
            'marker_border' => 'rgb(79 176 109 / 58%)',
            'theme_color' => '#040b07',
            'classes' => [
                'html' => 'world-theme-klassische-fantasy',
                'body' => 'world-theme-klassische-fantasy-shell',
            ],
            'css_variables' => [
                '--accent' => '#4fb06d',
                '--accent-strong' => 'rgb(79 176 109 / 22%)',
                '--world-bg-top' => 'rgb(25 86 55 / 30%)',
                '--world-bg-mid' => 'rgb(43 64 35 / 22%)',
                '--world-bg-bottom' => '#040b07',
                '--world-glow-primary' => 'rgb(79 176 109 / 24%)',
                '--world-glow-secondary' => 'rgb(215 197 109 / 16%)',
            ],
        ],
        'kriminalfaelle' => [
            'theme_key' => 'kriminalfaelle',
            'label' => 'Kriminalfälle',
            'marker_label' => 'K',
            'marker_symbol' => 'AKTE',
            'marker_bg' => 'rgb(39 29 22 / 90%)',
            'marker_fg' => '#f0d2a2',
            'marker_border' => 'rgb(183 121 69 / 58%)',
            'theme_color' => '#070707',
            'classes' => [
                'html' => 'world-theme-kriminalfaelle',
                'body' => 'world-theme-kriminalfaelle-shell',
            ],
            'css_variables' => [
                '--accent' => '#b77945',
                '--accent-strong' => 'rgb(183 121 69 / 22%)',
                '--world-bg-top' => 'rgb(72 47 33 / 32%)',
                '--world-bg-mid' => 'rgb(34 34 39 / 24%)',
                '--world-bg-bottom' => '#070707',
                '--world-glow-primary' => 'rgb(183 121 69 / 22%)',
                '--world-glow-secondary' => 'rgb(80 80 86 / 18%)',
            ],
        ],
        'gegenwart' => [
            'theme_key' => 'gegenwart',
            'label' => 'Gegenwart',
            'marker_label' => 'G',
            'marker_symbol' => 'JETZT',
            'marker_bg' => 'rgb(18 31 43 / 90%)',
            'marker_fg' => '#c7d7e6',
            'marker_border' => 'rgb(95 143 184 / 58%)',
            'theme_color' => '#05070a',
            'classes' => [
                'html' => 'world-theme-gegenwart',
                'body' => 'world-theme-gegenwart-shell',
            ],
            'css_variables' => [
                '--accent' => '#5f8fb8',
                '--accent-strong' => 'rgb(95 143 184 / 22%)',
                '--world-bg-top' => 'rgb(31 54 72 / 30%)',
                '--world-bg-mid' => 'rgb(30 38 48 / 24%)',
                '--world-bg-bottom' => '#05070a',
                '--world-glow-primary' => 'rgb(95 143 184 / 22%)',
                '--world-glow-secondary' => 'rgb(100 116 139 / 16%)',
            ],
        ],
        'sci-fi' => [
            'theme_key' => 'sci-fi',
            'label' => 'Sci-Fi',
            'marker_label' => 'SF',
            'marker_symbol' => 'STERNE',
            'marker_bg' => 'rgb(10 34 43 / 90%)',
            'marker_fg' => '#b8f3ff',
            'marker_border' => 'rgb(86 199 217 / 58%)',
            'theme_color' => '#03060a',
            'classes' => [
                'html' => 'world-theme-sci-fi',
                'body' => 'world-theme-sci-fi-shell',
            ],
            'css_variables' => [
                '--accent' => '#56c7d9',
                '--accent-strong' => 'rgb(86 199 217 / 22%)',
                '--world-bg-top' => 'rgb(24 79 92 / 30%)',
                '--world-bg-mid' => 'rgb(47 38 82 / 24%)',
                '--world-bg-bottom' => '#03060a',
                '--world-glow-primary' => 'rgb(86 199 217 / 24%)',
                '--world-glow-secondary' => 'rgb(139 92 246 / 16%)',
            ],
        ],
        'postapokalypse' => [
            'theme_key' => 'postapokalypse',
            'label' => 'Postapokalypse',
            'marker_label' => 'PA',
            'marker_symbol' => 'ROST',
            'marker_bg' => 'rgb(42 33 19 / 90%)',
            'marker_fg' => '#e2c08a',
            'marker_border' => 'rgb(164 111 58 / 58%)',
            'theme_color' => '#060604',
            'classes' => [
                'html' => 'world-theme-postapokalypse',
                'body' => 'world-theme-postapokalypse-shell',
            ],
            'css_variables' => [
                '--accent' => '#a46f3a',
                '--accent-strong' => 'rgb(164 111 58 / 22%)',
                '--world-bg-top' => 'rgb(87 65 34 / 30%)',
                '--world-bg-mid' => 'rgb(54 63 37 / 22%)',
                '--world-bg-bottom' => '#060604',
                '--world-glow-primary' => 'rgb(164 111 58 / 24%)',
                '--world-glow-secondary' => 'rgb(85 107 47 / 16%)',
            ],
        ],
    ],
];
