<?php

return [
    'species' => [
        'mensch' => [
            'label' => 'Mensch',
            'description' => 'Vielseitig, anpassungsfaehig und in fast jeder Welt verbreitet.',
            'modifiers' => [],
            'le_bonus' => 0,
            'ae_bonus' => 0,
            'is_magic_capable' => false,
        ],
        'elf' => [
            'label' => 'Elf',
            'description' => 'Feinsinnig und nah an verborgenen Stroemungen.',
            'modifiers' => [
                'in' => 10,
                'ch' => 10,
                'kk' => -5,
            ],
            'le_bonus' => 0,
            'ae_bonus' => 5,
            'is_magic_capable' => true,
        ],
        'zwerg' => [
            'label' => 'Zwerg',
            'description' => 'Zaeh, standhaft und von harter Disziplin gepraegt.',
            'modifiers' => [
                'kk' => 10,
                'ko' => 10,
                'ge' => -5,
                'ch' => -5,
            ],
            'le_bonus' => 5,
            'ae_bonus' => 0,
            'is_magic_capable' => false,
        ],
        'halbling' => [
            'label' => 'Halbling',
            'description' => 'Klein, flink und sozial gewandt, aber selten fronttauglich.',
            'modifiers' => [
                'ff' => 10,
                'ge' => 5,
                'kk' => -5,
            ],
            'le_bonus' => 0,
            'ae_bonus' => 0,
            'is_magic_capable' => false,
        ],
        'halbork' => [
            'label' => 'Halbork',
            'description' => 'Kraftvoll und einschuechternd, oft mit rauer Sozialpraesenz.',
            'modifiers' => [
                'kk' => 10,
                'mu' => 5,
                'ch' => -5,
                'ge' => -5,
            ],
            'le_bonus' => 3,
            'ae_bonus' => 0,
            'is_magic_capable' => false,
        ],
        'synthet' => [
            'label' => 'Synthet',
            'description' => 'Kuenstlich erzeugte Entitaet mit hoher Stabilitaet und Fokus.',
            'modifiers' => [
                'kl' => 5,
                'ko' => 5,
                'ch' => -5,
            ],
            'le_bonus' => 2,
            'ae_bonus' => 0,
            'is_magic_capable' => false,
        ],
        'genmod' => [
            'label' => 'Genmod',
            'description' => 'Biotechnisch optimierter Mensch mit messbaren Leistungsprofilen.',
            'modifiers' => [
                'ge' => 5,
                'ko' => 5,
                'in' => 5,
                'ch' => -5,
            ],
            'le_bonus' => 2,
            'ae_bonus' => 0,
            'is_magic_capable' => false,
        ],
        'xeno' => [
            'label' => 'Xeno',
            'description' => 'Nicht-menschliche Spezies mit ungewoehnlicher Wahrnehmung.',
            'modifiers' => [
                'in' => 10,
                'kl' => 5,
                'kk' => -5,
                'ch' => -5,
            ],
            'le_bonus' => 0,
            'ae_bonus' => 0,
            'is_magic_capable' => false,
        ],
        'mutant' => [
            'label' => 'Mutant',
            'description' => 'An die Nachwelt angepasst, widerstandsfaehig aber gesellschaftlich belastet.',
            'modifiers' => [
                'ko' => 10,
                'kk' => 5,
                'in' => -5,
                'ch' => -10,
            ],
            'le_bonus' => 4,
            'ae_bonus' => 0,
            'is_magic_capable' => false,
        ],
    ],

    'callings' => [
        'magier' => [
            'label' => 'Magier',
            'minimums' => ['kl' => 45, 'in' => 40],
            'bonuses' => ['ae_percent' => 10, 'attributes' => ['kl' => 5]],
            'description' => 'Du liest Muster in Asche und Sternen, wo andere nur Rauch sehen.',
            'is_magic_capable' => true,
            'is_custom' => false,
        ],
        'ritter' => [
            'label' => 'Ritter',
            'minimums' => ['mu' => 40, 'kk' => 40, 'ge' => 35],
            'bonuses' => ['le_flat' => 5, 'attributes' => ['mu' => 5]],
            'description' => 'Du lebst nach Eid und Klinge in einer Welt ohne klare Herrschaft.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'abenteurer' => [
            'label' => 'Abenteurer',
            'minimums' => ['mu' => 35, 'in' => 35],
            'bonuses' => ['attributes' => ['in' => 5, 'ge' => 5]],
            'description' => 'Du ueberlebst durch Instinkt, Tempo und den Mut zum falschen Weg.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'geistlicher' => [
            'label' => 'Geistlicher',
            'minimums' => ['ch' => 40, 'mu' => 35, 'kl' => 35],
            'bonuses' => ['ae_percent' => 10, 'attributes' => ['ch' => 5]],
            'description' => 'Du traegst Liturgie durch Ruinen und Hungerzeiten.',
            'is_magic_capable' => true,
            'is_custom' => false,
        ],
        'wissenschaftler' => [
            'label' => 'Wissenschaftler',
            'minimums' => ['kl' => 45, 'in' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'in' => 5]],
            'description' => 'Du sezierst Wahrheit mit kalter Praezision.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'dieb' => [
            'label' => 'Dieb',
            'minimums' => ['ff' => 45, 'ge' => 40, 'in' => 35],
            'bonuses' => ['attributes' => ['ff' => 5, 'ge' => 5]],
            'description' => 'Du nimmst, was gut bewacht ist, und verschwindest vor dem Echo.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'krieger' => [
            'label' => 'Krieger',
            'minimums' => ['kk' => 45, 'ko' => 40, 'mu' => 40],
            'bonuses' => ['le_flat' => 5, 'attributes' => ['kk' => 5]],
            'description' => 'Du entscheidest Konflikte dort, wo Worte laengst verbrannt sind.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'heiler' => [
            'label' => 'Heiler',
            'minimums' => ['kl' => 40, 'in' => 40, 'ch' => 35],
            'bonuses' => ['attributes' => ['in' => 5], 'ae_flat' => 5],
            'description' => 'Du kennst den Preis von Blut und Fieber besser als jeder Feldherr.',
            'is_magic_capable' => true,
            'is_custom' => false,
        ],
        'barde' => [
            'label' => 'Barde',
            'minimums' => ['ch' => 45, 'in' => 40, 'ff' => 35],
            'bonuses' => ['attributes' => ['ch' => 5, 'in' => 5]],
            'description' => 'Du lenkst Hallen mit Stimme, Vers und Luege.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'jaeger' => [
            'label' => 'Jaeger',
            'minimums' => ['in' => 40, 'ge' => 40, 'ko' => 35],
            'bonuses' => ['attributes' => ['in' => 5, 'ge' => 5]],
            'description' => 'Du liest Spuren in Nebel, Schlamm und Aschewind.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'schmied' => [
            'label' => 'Schmied',
            'minimums' => ['kk' => 45, 'ff' => 40, 'ko' => 40],
            'bonuses' => ['attributes' => ['ko' => 5, 'kk' => 5]],
            'description' => 'Du formst aus Erz und Feuer mehr als nur Stahl.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'gelehrter' => [
            'label' => 'Gelehrter',
            'minimums' => ['kl' => 50, 'in' => 40],
            'bonuses' => ['attributes' => ['kl' => 5, 'ch' => 5]],
            'description' => 'Du sammelst Fragmente gefallener Zeitalter und setzt sie zu Sinn zusammen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'paladin' => [
            'label' => 'Paladin',
            'minimums' => ['mu' => 40, 'ch' => 40, 'ko' => 35],
            'bonuses' => ['le_flat' => 4, 'attributes' => ['mu' => 5, 'ch' => 5]],
            'description' => 'Du vereinst Glauben, Schutzauftrag und frontnahe Disziplin.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'waldlaeufer' => [
            'label' => 'Waldlaeufer',
            'minimums' => ['in' => 40, 'ge' => 40, 'ff' => 35],
            'bonuses' => ['attributes' => ['in' => 5, 'ge' => 5]],
            'description' => 'Du bewegst dich in Grenzraeumen lautlos und praezise.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'schurke' => [
            'label' => 'Schurke',
            'minimums' => ['ff' => 45, 'ge' => 40, 'ch' => 35],
            'bonuses' => ['attributes' => ['ff' => 5, 'ch' => 5]],
            'description' => 'Du arbeitest aus Schattenpositionen mit Taktik statt roher Gewalt.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'kleriker' => [
            'label' => 'Kleriker',
            'minimums' => ['ch' => 40, 'kl' => 35, 'mu' => 35],
            'bonuses' => ['ae_percent' => 10, 'attributes' => ['ch' => 5]],
            'description' => 'Du verknuepfst Lehre, Seelsorge und rituelle Autoritaet.',
            'is_magic_capable' => true,
            'is_custom' => false,
        ],
        'alchemist' => [
            'label' => 'Alchemist',
            'minimums' => ['kl' => 45, 'ff' => 35, 'in' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'ff' => 5]],
            'description' => 'Du erzeugst Wirkung durch kontrollierte Reaktionen und Rezepturen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'handwerker' => [
            'label' => 'Handwerker',
            'minimums' => ['ff' => 40, 'kk' => 35, 'kl' => 35],
            'bonuses' => ['attributes' => ['ff' => 5, 'ko' => 5]],
            'description' => 'Du baust, reparierst und haeltst Strukturen funktionsfaehig.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'polizist' => [
            'label' => 'Polizist',
            'minimums' => ['mu' => 40, 'in' => 35, 'ko' => 35],
            'bonuses' => ['attributes' => ['mu' => 5, 'in' => 5]],
            'description' => 'Du handelst unter Druck in rechtlich gebundenen Einsatzlagen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'journalist' => [
            'label' => 'Journalist',
            'minimums' => ['ch' => 40, 'kl' => 40, 'in' => 35],
            'bonuses' => ['attributes' => ['ch' => 5, 'kl' => 5]],
            'description' => 'Du beschaffst, pruefst und veroeffentlichst belastbare Informationen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'arzt' => [
            'label' => 'Arzt',
            'minimums' => ['kl' => 45, 'in' => 40, 'ff' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'in' => 5]],
            'description' => 'Du triagierst, behandelst und entscheidest in Minutenfenstern.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'sanitaeter' => [
            'label' => 'Sanitaeter',
            'minimums' => ['in' => 40, 'ko' => 35, 'ff' => 35],
            'bonuses' => ['le_flat' => 3, 'attributes' => ['in' => 5]],
            'description' => 'Du stabilisierst Patienten in instabilen Einsatzumgebungen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'it_spezialist' => [
            'label' => 'IT-Spezialist',
            'minimums' => ['kl' => 45, 'ff' => 35, 'in' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'ff' => 5]],
            'description' => 'Du sicherst, analysierst und manipulierst digitale Systeme.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'anwalt' => [
            'label' => 'Anwalt',
            'minimums' => ['kl' => 40, 'ch' => 45, 'in' => 35],
            'bonuses' => ['attributes' => ['ch' => 5, 'kl' => 5]],
            'description' => 'Du setzt Interessen in formalisierten Konfliktarenen durch.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'soldat' => [
            'label' => 'Soldat',
            'minimums' => ['mu' => 40, 'ko' => 40, 'kk' => 35],
            'bonuses' => ['le_flat' => 4, 'attributes' => ['mu' => 5]],
            'description' => 'Du agierst diszipliniert in Bedrohungslagen mit hoher Last.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'sozialarbeiter' => [
            'label' => 'Sozialarbeiter',
            'minimums' => ['ch' => 40, 'in' => 40, 'kl' => 35],
            'bonuses' => ['attributes' => ['ch' => 5, 'in' => 5]],
            'description' => 'Du stabilisierst Menschen und Systeme in Krisenumfeldern.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'kommissar' => [
            'label' => 'Kommissar',
            'minimums' => ['kl' => 40, 'in' => 40, 'ch' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'in' => 5]],
            'description' => 'Du fuehrst Ermittlungen und priorisierst unter Unsicherheit.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'forensiker' => [
            'label' => 'Forensiker',
            'minimums' => ['kl' => 45, 'in' => 40, 'ff' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'ff' => 5]],
            'description' => 'Du sicherst Spuren und machst sie gerichtsverwertbar.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'profiler' => [
            'label' => 'Profiler',
            'minimums' => ['in' => 45, 'kl' => 40, 'ch' => 35],
            'bonuses' => ['attributes' => ['in' => 5, 'kl' => 5]],
            'description' => 'Du leitest Verhalten aus Daten, Mustern und Fehlern ab.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'gerichtsmediziner' => [
            'label' => 'Gerichtsmediziner',
            'minimums' => ['kl' => 45, 'ff' => 40, 'ko' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'ff' => 5]],
            'description' => 'Du uebersetzt medizinische Fakten in belastbare Beweise.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'kriminaltechniker' => [
            'label' => 'Kriminaltechniker',
            'minimums' => ['ff' => 45, 'kl' => 40, 'in' => 35],
            'bonuses' => ['attributes' => ['ff' => 5, 'kl' => 5]],
            'description' => 'Du verbindest Technik und Spurensicherung im Detail.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'verdeckter_ermittler' => [
            'label' => 'Verdeckter Ermittler',
            'minimums' => ['ch' => 40, 'in' => 40, 'ge' => 35],
            'bonuses' => ['attributes' => ['ch' => 5, 'ge' => 5]],
            'description' => 'Du agierst unter Legende und kontrollierst dein Risiko.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'staatsanwalt' => [
            'label' => 'Staatsanwalt',
            'minimums' => ['kl' => 45, 'ch' => 40, 'mu' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'ch' => 5]],
            'description' => 'Du fuehrst Verfahren mit Strategie, Druck und Beweiskette.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'privatermittler' => [
            'label' => 'Privatermittler',
            'minimums' => ['in' => 40, 'ge' => 35, 'ch' => 35],
            'bonuses' => ['attributes' => ['in' => 5, 'ff' => 5]],
            'description' => 'Du jagst Wahrheiten zwischen offizieller Luecke und Grauzone.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'pilot' => [
            'label' => 'Pilot',
            'minimums' => ['in' => 40, 'ge' => 40, 'kl' => 35],
            'bonuses' => ['attributes' => ['ge' => 5, 'in' => 5]],
            'description' => 'Du kontrollierst Bewegung in hochdynamischen 3D-Raeumen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'ingenieur' => [
            'label' => 'Ingenieur',
            'minimums' => ['kl' => 45, 'ff' => 40, 'in' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'ff' => 5]],
            'description' => 'Du baust und stabilisierst Systeme unter Ressourcenlimit.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'hacker' => [
            'label' => 'Hacker',
            'minimums' => ['kl' => 45, 'ff' => 40, 'in' => 35],
            'bonuses' => ['attributes' => ['kl' => 5, 'in' => 5]],
            'description' => 'Du brichst Sicherheitsgrenzen und liest fremde Strukturen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'sicherheitsoffizier' => [
            'label' => 'Sicherheitsoffizier',
            'minimums' => ['mu' => 40, 'ko' => 40, 'ge' => 35],
            'bonuses' => ['le_flat' => 4, 'attributes' => ['mu' => 5]],
            'description' => 'Du fuehrst Schutz- und Zugriffslagen in kritischen Bereichen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'wissenschaftsoffizier' => [
            'label' => 'Wissenschaftsoffizier',
            'minimums' => ['kl' => 50, 'in' => 40],
            'bonuses' => ['attributes' => ['kl' => 5, 'in' => 5]],
            'description' => 'Du leitest Analyse, Protokoll und Hypothesen unter Zeitdruck.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'diplomat' => [
            'label' => 'Diplomat',
            'minimums' => ['ch' => 45, 'kl' => 35, 'in' => 35],
            'bonuses' => ['attributes' => ['ch' => 5, 'in' => 5]],
            'description' => 'Du verhandelst Interessen zwischen asymmetrischen Parteien.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'schmuggler' => [
            'label' => 'Schmuggler',
            'minimums' => ['ge' => 40, 'in' => 40, 'ch' => 35],
            'bonuses' => ['attributes' => ['ge' => 5, 'ff' => 5]],
            'description' => 'Du bewegst Ware und Informationen durch gesperrte Netze.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'psioniker' => [
            'label' => 'Psioniker',
            'minimums' => ['kl' => 45, 'in' => 45, 'ch' => 35],
            'bonuses' => ['ae_percent' => 10, 'attributes' => ['kl' => 5]],
            'description' => 'Du nutzt mentale Felder statt klassischer Magie.',
            'is_magic_capable' => true,
            'is_custom' => false,
        ],
        'scavenger' => [
            'label' => 'Scavenger',
            'minimums' => ['in' => 40, 'ge' => 40, 'ko' => 35],
            'bonuses' => ['attributes' => ['in' => 5, 'ge' => 5]],
            'description' => 'Du findest verwertbare Ressourcen in toten Zonen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'techniker' => [
            'label' => 'Techniker',
            'minimums' => ['kl' => 40, 'ff' => 40, 'ko' => 35],
            'bonuses' => ['attributes' => ['ff' => 5, 'kl' => 5]],
            'description' => 'Du bringst alte Infrastruktur unter Notbedingungen zum Laufen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'feldsanitaeter' => [
            'label' => 'Feldsanitaeter',
            'minimums' => ['in' => 40, 'kl' => 40, 'ko' => 35],
            'bonuses' => ['le_flat' => 3, 'attributes' => ['in' => 5]],
            'description' => 'Du stabilisierst Verwundete in bewegten Kampfzonen.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'nomadenjaeger' => [
            'label' => 'Nomadenjaeger',
            'minimums' => ['in' => 40, 'ge' => 40, 'ko' => 40],
            'bonuses' => ['attributes' => ['in' => 5, 'ge' => 5]],
            'description' => 'Du fuehrst Gruppen sicher durch instabile Wildnisse.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'vollstrecker' => [
            'label' => 'Vollstrecker',
            'minimums' => ['mu' => 40, 'kk' => 40, 'ko' => 35],
            'bonuses' => ['le_flat' => 4, 'attributes' => ['kk' => 5]],
            'description' => 'Du setzt Ordnung in unsicheren Zonen gewaltsam durch.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'haendler' => [
            'label' => 'Haendler',
            'minimums' => ['ch' => 40, 'kl' => 35, 'in' => 35],
            'bonuses' => ['attributes' => ['ch' => 5, 'kl' => 5]],
            'description' => 'Du organisierst Versorgung in fragilen Oekonomien.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'kultist' => [
            'label' => 'Kultist',
            'minimums' => ['ch' => 40, 'mu' => 35, 'in' => 35],
            'bonuses' => ['attributes' => ['ch' => 5, 'in' => 5]],
            'description' => 'Du bindest Gruppen ueber Symbolik, Glaube und Kontrolle.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'aufklaerer' => [
            'label' => 'Aufklaerer',
            'minimums' => ['in' => 40, 'ge' => 40, 'ff' => 35],
            'bonuses' => ['attributes' => ['in' => 5, 'ge' => 5]],
            'description' => 'Du beschaffst Lagebilder, bevor Fronten eskalieren.',
            'is_magic_capable' => false,
            'is_custom' => false,
        ],
        'eigene' => [
            'label' => 'Eigene',
            'minimums' => [],
            'bonuses' => ['attributes' => []],
            'description' => 'Frei definierte Berufung fuer individuelle Konzepte.',
            'is_magic_capable' => false,
            'is_custom' => true,
        ],
    ],

    'templates' => [
        'chroniken-der-asche' => [
            'label' => 'Chroniken der Asche',
            'species' => ['mensch', 'elf', 'zwerg'],
            'callings' => ['magier', 'ritter', 'abenteurer', 'geistlicher', 'wissenschaftler', 'dieb', 'krieger', 'heiler', 'barde', 'jaeger', 'schmied', 'gelehrter', 'eigene'],
        ],
        'klassische-fantasy' => [
            'label' => 'Klassische Fantasy',
            'species' => ['mensch', 'elf', 'zwerg', 'halbling', 'halbork'],
            'callings' => ['magier', 'paladin', 'waldlaeufer', 'schurke', 'kleriker', 'barde', 'alchemist', 'handwerker', 'abenteurer', 'eigene'],
        ],
        'gegenwart' => [
            'label' => 'Gegenwart',
            'species' => ['mensch'],
            'callings' => ['polizist', 'journalist', 'arzt', 'sanitaeter', 'it_spezialist', 'anwalt', 'soldat', 'sozialarbeiter', 'eigene'],
        ],
        'kriminalfaelle' => [
            'label' => 'Kriminalfaelle',
            'species' => ['mensch'],
            'callings' => ['kommissar', 'forensiker', 'profiler', 'gerichtsmediziner', 'kriminaltechniker', 'verdeckter_ermittler', 'staatsanwalt', 'privatermittler', 'eigene'],
        ],
        'sci-fi' => [
            'label' => 'Sci-Fi',
            'species' => ['mensch', 'synthet', 'genmod', 'xeno'],
            'callings' => ['pilot', 'ingenieur', 'hacker', 'sicherheitsoffizier', 'wissenschaftsoffizier', 'diplomat', 'schmuggler', 'psioniker', 'eigene'],
        ],
        'postapokalypse' => [
            'label' => 'Postapokalypse',
            'species' => ['mensch', 'mutant', 'synthet'],
            'callings' => ['scavenger', 'techniker', 'feldsanitaeter', 'nomadenjaeger', 'vollstrecker', 'haendler', 'kultist', 'aufklaerer', 'eigene'],
        ],
    ],
];
